dataset: cifar10
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 4
- 5
- 7
- 10
- 13
- 17
- 23
- 30
- 40
- 54
- 71
- 95
fidelity_single: 5
max_hpo_time: 900
out_dir: p301_nohyper_0
predictor: gp
search_space: darts
seed: 27
test_size: 200
train_size_list:
- 5
- 8
- 12
- 20
- 31
- 50
- 79
- 126
- 199
- 316
- 500
train_size_single: 100
uniform_random: 1
